theme: jekyll-theme-cayman
title: UofG Luke Holland - Barclays Summer Internship
description: This webpage contains information about my internship and the project proposal derived from the internship.
